#' Prepare dynamic range data for a single source (LFQ or LBQ)
#'
#' Extracts and standardizes abundance information from input data for a specific source,
#' ranks the values by descending abundance, and tags the data with the source label.
#'
#' @param data A data frame containing abundance values. For LFQ, must include a column named
#'        `LogIntensities`; for LBQ, must include `Abundance`.
#' @param source Character string indicating the data source. Must be either `"LFQ"` or `"LBQ"`.
#'
#' @return A data frame with columns: `Abundance`, `Rank`, and `Source`.
get_dynamic_range_data_source <- function(data, source = c("LFQ", "LBQ")) {
  source <- match.arg(source)
  
  if (source == "LFQ") {
    data <- data %>%
      select(Abundance = LogIntensities)
  } else if (source == "LBQ") {
    data <- data %>%
      select(Abundance)
  }
  
  data <- data %>%
    arrange(desc(Abundance)) %>%
    mutate(Rank = seq_along(Abundance),
           Source = rep(source, nrow(.)))
  
  return(data)
}

#' Combine dynamic range data from LFQ and LBQ sources
#'
#' Applies `get_dynamic_range_data_source()` to LFQ and LBQ datasets and combines the results
#' into a single data frame for plotting or analysis.
#'
#' @param lfq_data A data frame containing LFQ intensity values in a `LogIntensities` column.
#' @param lbq_data A data frame containing LBQ abundance values in an `Abundance` column.
#'
#' @return A combined data frame with `Abundance`, `Rank`, and `Source` columns.
get_dynamic_range_data <- function(lfq_data, lbq_data) {
  lfq_data <- get_dynamic_range_data_source(lfq_data, "LFQ")
  lbq_data <- get_dynamic_range_data_source(lbq_data, "LBQ")
  
  bind_rows(lfq_data, lbq_data)
}

#' Generate a dynamic range scatter plot for LFQ and LBQ data
#'
#' Creates a faceted scatter plot of ranked abundance values for each source using ggplot2.
#' This plot helps visualize the dynamic range and intensity distribution of the measurements.
#'
#' @param dynamic_range_data A data frame generated by `get_dynamic_range_data()`,
#' with columns `Abundance`, `Rank`, and `Source`.
#'
#' @return A `ggplot` object showing the dynamic range for each source.
get_dynamic_range_plot <- function(dynamic_range_data) {
  ggplot(dynamic_range_data, aes(x = Rank, y = Abundance)) +
    facet_wrap( ~ factor(Source, levels = c("LFQ", "LBQ")), scales = "free") +
    geom_violin(color = hue_pal()(4)[1],
                fill = hue_pal()(4)[1],
                alpha = 0.5) +
    geom_point(alpha = 0.05) +
    labs(x = "Rank", y = "Abundance (arb. unit)") +
    scale_x_continuous(
      labels = function(x)
        format(x, scientific = TRUE)
    )
}